spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 625915571789-rsblbpcplatev0jf1dlirmpg8533thuc.apps.googleusercontent.com
            client-secret: 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